# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Horta Lliure
# Description of the Site
description: Creativitat, llibertat, ecologia i més cosetes.
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: Horta, Ecologia, linux, compostatge
# URL for the Image of custom Favicon
favicon-url: /assets/images/logo.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/meta.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: info.hortalliure@gmail.com
facebook_username: /
twitter_username: /
instagram_username: /
linkedin_username: /
github_username:  hortalliure
youtube_channel_id: /
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /
discord_username: hortalliure#7940

# Google Analytics
google-analytics: /

# Disqus
disqus-shortname: /
# Name of the Author
author-name: Horta Lliure
# URL for the Image of the Author
author-image: /assets/images/logo.png
# 60 Words About the Author
author-about: "Sóm un espai col·laboratiu de projectes educatius, creatius i lúdics amb l'objectiu de millorar la vida de les persones, des d'un punt de vista d'equitat social i millora del medi ambient."

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/hortalliure

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
